-- Method catalog seed (METHODS_V4 + interactive session methods from maquette)
insert into public.method_catalog (id, title, tagline, est_minutes, categories, icon, color, sort_order, interactive) values
  ('brainstorm', 'Brainstorming libre', 'Tableau blanc + post-it', 45, '{ideas,start,align}', 'Sparkles', 'green', 1, true),
  ('brainstorming', 'Brainstorming structurÃ©', 'Colonnes divergent / convergent', 45, '{ideas}', 'Sparkles', 'green', 2, true),
  ('ishikawa', 'Ishikawa', 'Causes / effets (arÃªte de poisson)', 75, '{reflect}', 'Sliders', 'violet', 3, true),
  ('fivewhys', '5 Pourquoi', 'Remonter Ã  la cause racine', 30, '{reflect,decide}', 'Target', 'blue', 4, true),
  ('5-pourquoi', '5 Pourquoi', 'Remonter Ã  la cause racine', 30, '{reflect,decide}', 'Target', 'blue', 5, true),
  ('concept', 'Carte conceptuelle', 'Concepts et liens', 45, '{study,align,stake}', 'Link', 'blue', 6, true),
  ('functional', 'SchÃ©ma fonctionnel', 'Fonctions et flux', 45, '{study,start}', 'Grid', 'green', 7, false),
  ('logic', 'SchÃ©ma logique', 'HiÃ©rarchie / arbre', 30, '{study,decide}', 'List', 'amber', 8, false),
  ('bono', 'Six Chapeaux de Bono', 'Un sujet sous six angles', 60, '{decide,reflect,ideas}', 'Eye', 'violet', 9, true),
  ('bmc', 'Business Model Canvas', 'ModÃ©liser sur une page', 60, '{start,stake}', 'FileText', 'blue', 10, true),
  ('qqoqcp', 'QQOQCP', 'Qui, Quoi, OÃ¹, Quand, Comment, Pourquoi', 45, '{start,align}', 'HelpCircle', 'blue', 11, true),
  ('swot', 'SWOT', 'Forces, Faiblesses, OpportunitÃ©s, Menaces', 45, '{reflect,decide}', 'Grid', 'violet', 12, true),
  ('pestel', 'PESTEL', 'Analyse macro-environnement', 45, '{reflect,study}', 'Globe', 'amber', 13, true),
  ('brainwriting', 'Brainwriting', 'IdÃ©ation silencieuse par Ã©crit', 40, '{ideas}', 'Pencil', 'green', 14, true),
  ('bw635', 'Brainwriting 6-3-5', '6 participants, 3 idÃ©es, 5 tours', 45, '{ideas}', 'Users', 'green', 15, true),
  ('scamper', 'SCAMPER', 'Substituer, Combiner, Adapterâ€¦', 45, '{ideas}', 'Lightbulb', 'amber', 16, true),
  ('carte-d-empathie', 'Carte d''empathie', 'Voir, entendre, penser, ressentir', 50, '{stake,study}', 'Heart', 'red', 17, true),
  ('analyse-des-parties-prenantes', 'Parties prenantes', 'Cartographier les acteurs', 45, '{stake,align}', 'Users', 'blue', 18, true),
  ('analyse-des-risques', 'Analyse des risques', 'ProbabilitÃ© Ã— impact', 50, '{reflect,decide}', 'AlertTriangle', 'red', 19, true),
  ('benchmark-concurrentiel', 'Benchmark concurrentiel', 'Comparer avec le marchÃ©', 45, '{study,decide}', 'BarChart', 'violet', 20, true),
  ('clarification-du-mandat', 'Clarification du mandat', 'Cadrer le pÃ©rimÃ¨tre', 40, '{start,align}', 'Clipboard', 'blue', 21, true),
  ('lean-canvas', 'Lean Canvas', 'HypothÃ¨ses et risques startup', 50, '{start}', 'Layers', 'amber', 22, true),
  ('matrice-pouvoir-interet', 'Matrice pouvoir / intÃ©rÃªt', 'Prioriser les parties prenantes', 40, '{stake,decide}', 'Grid', 'violet', 23, true),
  ('objectifs-smart', 'Objectifs SMART', 'SpÃ©cifique, Mesurable, Atteignableâ€¦', 35, '{decide,start}', 'Target', 'green', 24, true),
  ('persona', 'Persona', 'Profil utilisateur type', 45, '{stake,study}', 'User', 'blue', 25, true),
  ('parcours-utilisateur', 'Parcours utilisateur', 'Ã‰tapes, Ã©motions, frictions', 55, '{stake,study}', 'Route', 'violet', 26, true),
  ('value-proposition-canvas', 'Value Proposition Canvas', 'Proposition de valeur', 50, '{start,stake}', 'Sparkles', 'amber', 27, true),
  ('matrice-impact-effort', 'Matrice Impact / Effort', 'Prioriser les actions', 40, '{decide}', 'Grid', 'green', 28, true),
  ('moscow', 'MoSCoW', 'Must, Should, Could, Won''t', 35, '{decide}', 'List', 'blue', 29, true),
  ('start-stop-continue', 'Start / Stop / Continue', 'RÃ©trospective rapide', 30, '{reflect,align}', 'RefreshCw', 'green', 30, true),
  ('retrospective-4l', 'RÃ©trospective 4L', 'Liked, Learned, Lacked, Longed for', 40, '{reflect}', 'Heart', 'violet', 31, true),
  ('rice', 'RICE', 'Reach, Impact, Confidence, Effort', 35, '{decide}', 'BarChart', 'blue', 32, true),
  ('plan-d-action', 'Plan d''action', 'Qui fait quoi, quand', 30, '{decide,align}', 'CheckSquare', 'green', 33, true),
  ('kanban', 'Kanban', 'Flux visuel des tÃ¢ches', 45, '{align,decide}', 'Columns', 'blue', 34, true),
  ('scrum-sprint-board', 'Scrum Sprint Board', 'Sprint backlog et avancement', 50, '{align}', 'Layout', 'violet', 35, true),
  ('gantt-simplifie', 'Gantt simplifiÃ©', 'Planning temporel', 45, '{align,start}', 'Calendar', 'amber', 36, true),
  ('raci', 'Matrice RACI', 'Responsable, Approbateur, ConsultÃ©, InformÃ©', 40, '{align,decide}', 'Users', 'blue', 37, true),
  ('tracabilite', 'TraÃ§abilitÃ©', 'Suivi des dÃ©cisions et actions', 30, '{align}', 'Link', 'slate', 38, true)
on conflict (id) do update set
  title = excluded.title,
  tagline = excluded.tagline,
  est_minutes = excluded.est_minutes,
  categories = excluded.categories,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order,
  interactive = excluded.interactive;

